In [1]:
import sys
import os
import importlib
import pandas as pd

sys.path.append(os.path.abspath(".."))

import src.models.compare_models as cm
importlib.reload(cm)

from src.models.compare_models import compare_models

# Modelos varias variables

In [2]:
from src.features.preprocessing import preprocessing

In [4]:
import sys
import os
import importlib
import warnings
warnings.filterwarnings("ignore")

sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))
import src.features.preprocessing as prep
importlib.reload(prep) 
df, x, y = prep.preprocessing()

df.head(5)

,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,es_muy_larga,genre_grouped
0,0,0.611,0.389,99373,0.910,0.000,C#,0.3460,-1.828,Major,0.0525,166.969,4/4,0.814,False,soundtrack
1,1,0.246,0.590,137373,0.737,0.000,F#,0.1510,-5.559,Minor,0.0868,174.003,4/4,0.816,False,soundtrack
2,3,0.952,0.663,170267,0.131,0.000,C,0.1030,-13.879,Minor,0.0362,99.488,5/4,0.368,False,soundtrack
3,0,0.703,0.240,152427,0.326,0.000,C#,0.0985,-12.178,Major,0.0395,171.758,4/4,0.227,False,soundtrack
4,4,0.950,0.331,82625,0.225,0.123,F,0.2020,-21.150,Major,0.0456,140.576,4/4,0.390,False,soundtrack

In [6]:
results = compare_models(x, y)

Entrenando Logistic Regression...
Entrenando Random Forest...
Entrenando Gradient Boosting...
Entrenando KNN...

In [7]:
import pandas as pd

summary = []

for model_name, result in results.items():
    report = result["report"]
    summary.append({
        "Modelo": model_name,
        "Accuracy": report["accuracy"],
        "Macro Recall": report["macro avg"]["recall"],
        "Macro F1": report["macro avg"]["f1-score"],
        "Weighted F1": report["weighted avg"]["f1-score"]
    })

# Ordenar por lo que definiste como prioridad
summary_df = pd.DataFrame(summary).sort_values(
    by=["Macro Recall", "Macro F1"], 
    ascending=False
)

summary_df

                Modelo  Accuracy  Macro Recall  Macro F1  Weighted F1
1        Random Forest  0.584544      0.553864  0.571585     0.577776
2    Gradient Boosting  0.612769      0.551017  0.577818     0.598001
3                  KNN  0.525580      0.499110  0.506449     0.520421
0  Logistic Regression  0.539725      0.458723  0.469596     0.506901